In [1]:
import numpy as np
import torch

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
# 데이터타입을 나타낸다
x_data.dtype

torch.int64

In [5]:
# 랜덤하게 tensor 초기화방법

shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.7303, 0.6759, 0.3764],
        [0.0401, 0.7816, 0.6195]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [6]:
# numpy배열 방법으로 Tensor 초기화

In [7]:
data = [[1,2], [3,4]]
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [8]:
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [9]:
x_np.dtype

torch.int32

In [10]:
# torch.float32 형식으로 초기화

data = [[1,2],[3,4]]
x_data = torch.tensor(data, dtype=torch.float32)

In [11]:
x_data

tensor([[1., 2.],
        [3., 4.]])

In [12]:
x_data.dtype

torch.float32

In [13]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data, dtype=torch.uint8)


In [14]:
x_data

tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)

In [15]:
x_data.dtype

torch.uint8

In [16]:
torch.cuda.is_available()

True

In [17]:
x_data  = x_data.to("cuda")

In [18]:
# 어떤 디바이스에 텐서가 위치해 있는가 확인
x_data.device

device(type='cuda', index=0)

In [19]:
tensor = torch.ones(4,4)

In [20]:
print(f"First row : {tensor[0]}")
print(f"First column: {tensor[:,0]}")
print(f"Last column: {tensor[:,-1]}")
tensor[:,1] = 0
print(tensor)

First row : tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [21]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

In [22]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

In [23]:
z1 = tensor * tensor
z2 = tensor.mul(tensor)

In [24]:
z1

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [25]:
z2

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [26]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [27]:
tensor.add_(5)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

In [28]:
tensor

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])